# Site settings
title: Nat Tuck
email: "ntuck ⚓ ccs.neu.edu"
description: > # this means to ignore newlines until "baseurl:"
    Nat Tuck, CCS Lecturer @ Northeastern
baseurl: "/home/ntuck" # the subpath of your site, e.g. /blog/
url: "http://ccs.neu.edu" # the base hostname & protocol for your site
twitter_username: 
github_username:  NatTuck

# Build settings
markdown: kramdown
